FACULTY_DEPARTMENT_CHOICES = (
    ('CSE','COMPUTER SCIENCE AND ENGINEERING'),
    ('ECE','ELECTRONICS AND COMMUNICATION ENGINEERING'),
    ('EEE','ELECTRICAL AND ELECTRONICS ENGINEERING'),
    ('EIE','ELECTRONICS AND INSTRUMENTATION ENGINEERING')
    
)

FACULTY_DEPARTMENT_FULL_NAME = {"COMPUTER SCIENCE AND ENGINEERING","ELECTRONICS AND COMMUNICATION ENGINEERING","ELECTRICAL AND ELECTRONICS ENGINEERING","ELECTRONICS AND INSTRUMENTATION ENGINEERING"}
FACULTY_DEPARTMENT = {'CSE','ECE','EEE','EIE'}