# Generated by Django 3.2.8 on 2023-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_faculty_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='subject_assigned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
