# Generated by Django 3.2.8 on 2023-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_faculty_subject_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='subject_assigned',
            new_name='subject_1',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
