# Generated by Django 3.2.8 on 2023-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_auto_20230430_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject_1',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subject_2',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subject_3',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject_preference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
