# Generated by Django 3.2.8 on 2023-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_auto_20230430_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty_allocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
