# Generated by Django 3.2.8 on 2023-05-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_subject_faculty_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='faculty_allocation',
            new_name='faculty_allocated',
        ),
    ]
