# Generated by Django 3.2.8 on 2023-04-12 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=15)),
                ('role_type', models.CharField(choices=[('BASIC', 'BASIC'), ('ADMIN', 'ADMIN'), ('SUPER_ADMIN', 'SUPER ADMIN')], default='BASIC', max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('game_ids', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile_data',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profile_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to='account.profiledata'),
        ),
    ]
