# Generated by Django 3.2.8 on 2023-04-12 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230412_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_data',
        ),
        migrations.AddField(
            model_name='profiledata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
