# Generated by Django 4.2 on 2023-04-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230412_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='status',
        ),
    ]
