# Generated by Django 3.2.8 on 2023-04-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profiledata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='game_ids',
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.user'),
        ),
    ]
